#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication11
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
	public partial class databaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMusteri(Musteri instance);
    partial void UpdateMusteri(Musteri instance);
    partial void DeleteMusteri(Musteri instance);
    partial void InsertÜrün(Ürün instance);
    partial void UpdateÜrün(Ürün instance);
    partial void DeleteÜrün(Ürün instance);
    partial void InsertUyeler(Uyeler instance);
    partial void UpdateUyeler(Uyeler instance);
    partial void DeleteUyeler(Uyeler instance);
    #endregion
		
		public databaseDataContext() : 
				base(global::WindowsFormsApplication11.Properties.Settings.Default.DatabaseConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Musteri> Musteris
		{
			get
			{
				return this.GetTable<Musteri>();
			}
		}
		
		public System.Data.Linq.Table<Ürün> Ürüns
		{
			get
			{
				return this.GetTable<Ürün>();
			}
		}
		
		public System.Data.Linq.Table<Uyeler> Uyelers
		{
			get
			{
				return this.GetTable<Uyeler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Musteri")]
	public partial class Musteri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RefNum;
		
		private string _GondAdSoyad;
		
		private System.Nullable<long> _GondTel;
		
		private string _GondSehir;
		
		private string _GondAdres;
		
		private string _AliciAdSoyad;
		
		private System.Nullable<long> _AliciTel;
		
		private string _AliciSehir;
		
		private string _AliciAdres;
		
		private EntitySet<Ürün> _Ürüns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRefNumChanging(int value);
    partial void OnRefNumChanged();
    partial void OnGondAdSoyadChanging(string value);
    partial void OnGondAdSoyadChanged();
    partial void OnGondTelChanging(System.Nullable<long> value);
    partial void OnGondTelChanged();
    partial void OnGondSehirChanging(string value);
    partial void OnGondSehirChanged();
    partial void OnGondAdresChanging(string value);
    partial void OnGondAdresChanged();
    partial void OnAliciAdSoyadChanging(string value);
    partial void OnAliciAdSoyadChanged();
    partial void OnAliciTelChanging(System.Nullable<long> value);
    partial void OnAliciTelChanged();
    partial void OnAliciSehirChanging(string value);
    partial void OnAliciSehirChanged();
    partial void OnAliciAdresChanging(string value);
    partial void OnAliciAdresChanged();
    #endregion
		
		public Musteri()
		{
			this._Ürüns = new EntitySet<Ürün>(new Action<Ürün>(this.attach_Ürüns), new Action<Ürün>(this.detach_Ürüns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefNum", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RefNum
		{
			get
			{
				return this._RefNum;
			}
			set
			{
				if ((this._RefNum != value))
				{
					this.OnRefNumChanging(value);
					this.SendPropertyChanging();
					this._RefNum = value;
					this.SendPropertyChanged("RefNum");
					this.OnRefNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GondAdSoyad", DbType="NVarChar(50)")]
		public string GondAdSoyad
		{
			get
			{
				return this._GondAdSoyad;
			}
			set
			{
				if ((this._GondAdSoyad != value))
				{
					this.OnGondAdSoyadChanging(value);
					this.SendPropertyChanging();
					this._GondAdSoyad = value;
					this.SendPropertyChanged("GondAdSoyad");
					this.OnGondAdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GondTel", DbType="BigInt")]
		public System.Nullable<long> GondTel
		{
			get
			{
				return this._GondTel;
			}
			set
			{
				if ((this._GondTel != value))
				{
					this.OnGondTelChanging(value);
					this.SendPropertyChanging();
					this._GondTel = value;
					this.SendPropertyChanged("GondTel");
					this.OnGondTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GondSehir", DbType="NVarChar(50)")]
		public string GondSehir
		{
			get
			{
				return this._GondSehir;
			}
			set
			{
				if ((this._GondSehir != value))
				{
					this.OnGondSehirChanging(value);
					this.SendPropertyChanging();
					this._GondSehir = value;
					this.SendPropertyChanged("GondSehir");
					this.OnGondSehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GondAdres", DbType="NVarChar(50)")]
		public string GondAdres
		{
			get
			{
				return this._GondAdres;
			}
			set
			{
				if ((this._GondAdres != value))
				{
					this.OnGondAdresChanging(value);
					this.SendPropertyChanging();
					this._GondAdres = value;
					this.SendPropertyChanged("GondAdres");
					this.OnGondAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AliciAdSoyad", DbType="NChar(10)")]
		public string AliciAdSoyad
		{
			get
			{
				return this._AliciAdSoyad;
			}
			set
			{
				if ((this._AliciAdSoyad != value))
				{
					this.OnAliciAdSoyadChanging(value);
					this.SendPropertyChanging();
					this._AliciAdSoyad = value;
					this.SendPropertyChanged("AliciAdSoyad");
					this.OnAliciAdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AliciTel", DbType="BigInt")]
		public System.Nullable<long> AliciTel
		{
			get
			{
				return this._AliciTel;
			}
			set
			{
				if ((this._AliciTel != value))
				{
					this.OnAliciTelChanging(value);
					this.SendPropertyChanging();
					this._AliciTel = value;
					this.SendPropertyChanged("AliciTel");
					this.OnAliciTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AliciSehir", DbType="NVarChar(50)")]
		public string AliciSehir
		{
			get
			{
				return this._AliciSehir;
			}
			set
			{
				if ((this._AliciSehir != value))
				{
					this.OnAliciSehirChanging(value);
					this.SendPropertyChanging();
					this._AliciSehir = value;
					this.SendPropertyChanged("AliciSehir");
					this.OnAliciSehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AliciAdres", DbType="NVarChar(50)")]
		public string AliciAdres
		{
			get
			{
				return this._AliciAdres;
			}
			set
			{
				if ((this._AliciAdres != value))
				{
					this.OnAliciAdresChanging(value);
					this.SendPropertyChanging();
					this._AliciAdres = value;
					this.SendPropertyChanged("AliciAdres");
					this.OnAliciAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteri_Ürün", Storage="_Ürüns", ThisKey="RefNum", OtherKey="RefNum")]
		public EntitySet<Ürün> Ürüns
		{
			get
			{
				return this._Ürüns;
			}
			set
			{
				this._Ürüns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ürüns(Ürün entity)
		{
			this.SendPropertyChanging();
			entity.Musteri = this;
		}
		
		private void detach_Ürüns(Ürün entity)
		{
			this.SendPropertyChanging();
			entity.Musteri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ürün")]
	public partial class Ürün : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RefNum;
		
		private string _YükTürü;
		
		private System.Nullable<int> _YükMiktarı;
		
		private System.Nullable<System.DateTime> _TeslimTarihi;
		
		private EntityRef<Musteri> _Musteri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRefNumChanging(int value);
    partial void OnRefNumChanged();
    partial void OnYükTürüChanging(string value);
    partial void OnYükTürüChanged();
    partial void OnYükMiktarıChanging(System.Nullable<int> value);
    partial void OnYükMiktarıChanged();
    partial void OnTeslimTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnTeslimTarihiChanged();
    #endregion
		
		public Ürün()
		{
			this._Musteri = default(EntityRef<Musteri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefNum", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RefNum
		{
			get
			{
				return this._RefNum;
			}
			set
			{
				if ((this._RefNum != value))
				{
					if (this._Musteri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRefNumChanging(value);
					this.SendPropertyChanging();
					this._RefNum = value;
					this.SendPropertyChanged("RefNum");
					this.OnRefNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YükTürü", DbType="NVarChar(50)")]
		public string YükTürü
		{
			get
			{
				return this._YükTürü;
			}
			set
			{
				if ((this._YükTürü != value))
				{
					this.OnYükTürüChanging(value);
					this.SendPropertyChanging();
					this._YükTürü = value;
					this.SendPropertyChanged("YükTürü");
					this.OnYükTürüChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YükMiktarı", DbType="Int")]
		public System.Nullable<int> YükMiktarı
		{
			get
			{
				return this._YükMiktarı;
			}
			set
			{
				if ((this._YükMiktarı != value))
				{
					this.OnYükMiktarıChanging(value);
					this.SendPropertyChanging();
					this._YükMiktarı = value;
					this.SendPropertyChanged("YükMiktarı");
					this.OnYükMiktarıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeslimTarihi", DbType="DateTime")]
		public System.Nullable<System.DateTime> TeslimTarihi
		{
			get
			{
				return this._TeslimTarihi;
			}
			set
			{
				if ((this._TeslimTarihi != value))
				{
					this.OnTeslimTarihiChanging(value);
					this.SendPropertyChanging();
					this._TeslimTarihi = value;
					this.SendPropertyChanged("TeslimTarihi");
					this.OnTeslimTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteri_Ürün", Storage="_Musteri", ThisKey="RefNum", OtherKey="RefNum", IsForeignKey=true)]
		public Musteri Musteri
		{
			get
			{
				return this._Musteri.Entity;
			}
			set
			{
				Musteri previousValue = this._Musteri.Entity;
				if (((previousValue != value) 
							|| (this._Musteri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Musteri.Entity = null;
						previousValue.Ürüns.Remove(this);
					}
					this._Musteri.Entity = value;
					if ((value != null))
					{
						value.Ürüns.Add(this);
						this._RefNum = value.RefNum;
					}
					else
					{
						this._RefNum = default(int);
					}
					this.SendPropertyChanged("Musteri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Uyeler")]
	public partial class Uyeler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ad;
		
		private System.Nullable<int> _sifre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    partial void OnsifreChanging(System.Nullable<int> value);
    partial void OnsifreChanged();
    #endregion
		
		public Uyeler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="Int")]
		public System.Nullable<int> sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
